[project]
name = "1c-accounting-mcp"
version = "1.0.1"
description = "1C Enterprise Accounting MCP server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp>=1.0.0",
    "fastmcp>=0.1.0",
    "python-dotenv>=1.0.0"
]
